### ISSUE TITLE
Delete 'dev' branch then clone master to dev

### ISSUE THREAD

**Issue by MarlonJD** [teamCandle/candle-python#11]
I away from the keyboard. Can someone delete the dev branch then clone master and create dev again ?

**Comment by bhavik-knight** [comment]
I'm on it!

**Comment by MarlonJD** [comment]
Thank you :+1:

**Comment by bhavik-knight** [comment]
It doesn't delete here, I don't know why!
I did
`git branch -D -r origin:dev`
which showed me 

![image](https://user-images.githubusercontent.com/15388512/51804168-6b6ee280-2283-11e9-9f31-2b0d11ffdfb3.png)

**Comment by bhavik-knight** [comment]
okay done, right command was
`git push origin -d <branchname>`

**Comment by bhavik-knight** [comment]
Actually, we don't need to clone master to dev!
When we make a new branch, master's components are already in it! And we can readily work on it! :)

**Comment by MarlonJD** [comment]
Yes just checkout the branch and commit anything our dev branch will be ready

**Comment by MarlonJD** [comment]
Thank you so much. But in readme say 'dev' branch. Now it shouldn't be null branch. Can you open 'dev' branch at least for now

**Comment by bhavik-knight** [comment]
sure!

**Comment by MarlonJD** [comment]
Awesome, thanks :+1:

**Comment by bhavik-knight** [comment]
I use `ssh` to clone/push, etc. Who likes to keep copy-pasting long passwords everytime from a password manager! 😅
